sudo: required
dist: trusty
env:
  global:
    - secure: "pQ7B5ZZ6Afsw8SxdyaWictH6V0K7eHPZbMYnJNfLc9ejHxWy+tK9K0J2Gd6x3wjVCMMVfzUbVyY3u3ZraqITgQa0C1tzbjl40TrD0twJjD/H1WQQGfOkXNQ+D21ehffBPkCvjG0uRY/eP1K3XJNGDUXms81HOs+AEf9GjFtai3/xfRjAvHmpx4KkDJ5sI2jP6svNfFARo5t3AKHu3JsY891knk9kMwNPVWHeRmDiI51KmXSA+hjxdfDC4jR0jWK9pAp4jOf87eYRzPHLyifejfw4cAG2NJy9fPUxQG1mFoNuIi1BD+3FN4EupFOXfN4Y0XkElLhEeqiaexXrKljYj9v6h55G/pQ+pj7OvmE/lsqrWtv7x/l2ISPTlJ1zlCEtNgBghSUb854/9zpwbAFxCNKDXZ8VgRqyv9ISLzwxRFKSdFzDEX/Zqg7aouCh2uMSGmHcGmlfVXYWHrZZcqLDwqaGmlwtOe+om6eD/lvglHIb1s7++H5EAgyIl/JY4XzOSn8RXxj6TdTOT4SuuBlTKtQvUSjSeM7yhFkGgh0yyBAgmeWwT3D0WdIkBm2fWrPdpJzZwUCuP1JGXLF8G0IpOH3EH0UHlWAdZVDrb3OQPDxqzcamNUuYZ0uGRB+qmHgb15dF0GVLdTYocMZC5bEkhQUeVKeKKSpvabiUGAvoERE="

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends texlive-xetex texlive-fonts-recommended lmodern texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-xcolor texlive-bibtex-extra

script:
  - make

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    email: kratsg@gmail.com
    name: Giordon Stark

notifications:
  email:
    on_success: never
    on_failure: always
